from typing import Tuple, Union, List, Sequence


class Tensor:
    def __init__(self, shape: Sequence[int]) -> None: ...
    def fill(self, value: Union[int, float]) -> None: ...
    def shape(self) -> Tuple[int, ...]: ...
    def data(self) -> List[Union[int, float]]: ...
    def add(self, other: 'Tensor') -> None: ...
    def matmul(self, other: 'Tensor') -> None: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: Union[int, float]) -> None: ...

def add(a: Tensor, b: Tensor) -> Tensor: ...
def matmul(a: Tensor, b: Tensor) -> Tensor: ...