

# Checks if CUDA-compatible GPU devices are available on the system.
def is_cuda_available() -> bool: ...

# Returns the number of CUDA-compatible GPU devices available.
def number_cuda_devices() -> int: ...

def list_cuda_devices() -> list[str]: ...

def current_cuda_device() -> int: ...

def device_details(device: int) -> str: ...

def set_cuda_device(device: int) -> None: ...