
def is_cuda_available() -> bool: ...
def number_cuda_devices() -> int: ...
def list_cuda_devices() -> list[str]: ...
def current_cuda_device() -> int: ...
def device_details(device: int) -> str: ...
def set_cuda_device(device: int) -> None: ...