from typing import Tuple, Union, List, Sequence


class Tensor:
    def __init__(self, shape: Union[Tuple[int, ...], List[int]], data: Union[None, List[float]] = None) -> None: ...
    def get(self, indices: Union[int, Tuple[int, ...]]) -> float: ...
    def set(self, indices: Union[int, Tuple[int, ...]], value: float) -> None: ...
    def get_shape(self) -> Tuple[int, ...]: ...
    def get_num_elements(self) -> int: ...
    def get_current_device_id(self) -> int: ...
    def to_cpu(self) -> None: ...
    def to_gpu(self, device_id: int) -> None: ...
    def add(self, other: 'Tensor') -> 'Tensor': ...
    def multiply(self, other: 'Tensor') -> 'Tensor': ...